version: '3.8'

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: materials_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Akrawer1
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis-data:/data
    command: redis-server --appendonly yes
