version: '3.8'

volumes:
  postgres-materials-data:
    driver: local
  postgres-users-data:
    driver: local
  redis-data:
    driver: local

services:
  postgres-materials:
    image: postgres
    container_name: postgres-materials-container
    restart: always
    environment:
      POSTGRES_DB: materials_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Akrawer1
    ports:
      - "5432:5432"
    volumes:
      - ./docker/data/postgres-materials-data:/var/lib/postgresql/data

  postgres-users:
    image: postgres
    container_name: postgres-users-container
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Akrawer1
    ports:
      - "5433:5432"
    volumes:
      - ./docker/data/postgres-users-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis-data:/data
    command: redis-server --appendonly yes
