spring:
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost,http://localhost:80,http://88.201.220.74,http://88.201.220.74:80}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600 